# Generated by Django 3.0.2 on 2020-01-22 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pladform', '0002_auto_20200119_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата активации')),
                ('end_date', models.DateField(verbose_name='Дата окончания (включительно)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pladform.Author', verbose_name='Пользователь')),
            ],
        ),
    ]
